### ISSUE TITLE
Создать и заполнить раздел Keynote Speakers

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web21#11]
@timac11 @larioandr 
Необходимо создать раздел Keynote Speakers (https://2021.dccn.ru/#keynotes) по подобию https://2020.dccn.ru/#keynotes.

Контент для раздела прилагается.  

Пока не поступила информация от Giuseppe Araniti, поэтому про него пишем TBA.

[Пленарные.zip](https://github.com/dccnconf/web21/files/6447481/default.zip)

**Comment by kozyrevdv** [comment]
Спикеров нужно разместить в следующем порядке:
| Trivedi | Correia |
|---------|---------|
| Levner  | Araniti |
| Sztrik  |         |

**Comment by kozyrevdv** [comment]
@timac11 

Просьба в https://2021.dccn.ru/#keynotes заполнить информацию о Giuseppe Araniti (прикрепляю)
[Abstract & Bio_Giuseppe Araniti.docx](https://github.com/dccnconf/web21/files/6527823/Abstract.Bio_Giuseppe.Araniti.docx)

**Comment by timac11** [comment]
@kozyrevdv done
