### ISSUE TITLE
Registration & Fees

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web21#3]
Необходимо на сайте 2021.dccn.ru добавить подраздел "Registration & Fees", как это было на https://2020.dccn.ru/#fees

Стоимость участия изменена:

- Russian citizens and students of Russian universities with co-authors | **5000** RUB (NO IEEE MEMBERSHIP) | **4250** RUB -15% (IEEE MEMBER)

- Students of Russian universities without co-authors | 500 RUB (NO IEEE MEMBERSHIP) | 0 RUB-100% (IEEE MEMBER) (без изменений)

- International participants | **180** EUR (NO IEEE MEMBERSHIP) | **153** EUR -15% (IEEE MEMBER)

**Comment by kozyrevdv** [comment]
Старый файл нужно соответственно заменить на новый:

[DCCN2021_FEES.pdf](https://github.com/dccnconf/web21/files/6001903/DCCN2021_FEES.pdf)

**Comment by timac11** [comment]
fixed in main branch
