### ISSUE TITLE
DCCN-2021: Proceedings

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web21#41]
@timac11 

Просьба обновить на сайте прошлого года раздел Springer Proceedings: https://2021.dccn.ru/#proceedings

Обновленный текст:
We are pleased to announce that both of the DCCN 2021 post-proceedings books (LNCS, volume 13144, and CCIS, volume 1552) has been published by Springer Nature. The books are available online. 

LNCS 13144:
https://link.springer.com/book/10.1007/978-3-030-92507-9

The conference participants are granted the four weeks free online access to the e-book of the LNCS proceedings.

CCIS 1552:
https://link.springer.com/book/10.1007/978-3-030-97110-6

The access to the CCIS volume is granted for the period from March 7 to April 7, 2022. 

Картинки:
![CCIS_обложка](https://user-images.githubusercontent.com/47321403/156569290-84b59cfc-a59a-481b-9ea0-8b2312684718.png)
![LNCS_обложка](https://user-images.githubusercontent.com/47321403/156569297-a5a373aa-0e8e-4e43-8cdb-e91c600a968f.png)

**Comment by kozyrevdv** [comment]
@timac11 

issue https://github.com/dccnconf/web21/issues/40 еще открыт...

**Comment by timac11** [comment]
@kozyrevdv что там не так ?

**Comment by timac11** [comment]
вроде я всё добавил и по той и по другой ише

**Comment by kozyrevdv** [comment]
Саш, issue 41 касался сайта dccn 2021. Ты не на том сайте разместил инфо...

сб, 5 мар. 2022 г., 9:25 timac11 ***@***.***>:

**Comment by timac11** [comment]
окей, во избежание таких ситуаций тогда попрошу здесь заводить для 2021, для 2022 заводить здесь https://github.com/dccnconf/web22/issues

**Comment by kozyrevdv** [comment]
Ok

сб, 5 мар. 2022 г., 9:59 timac11 ***@***.***>:

**Comment by timac11** [comment]
переделал

**Comment by kozyrevdv** [comment]
Супер! Спасибо.

сб, 5 мар. 2022 г. в 10:23, timac11 ***@***.***>:
