### ISSUE TITLE
раздел Authors

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web21#5]
Необходимо заполнить раздел Authors (https://2021.dccn.ru/authors) по принципу как это было на https://2020.dccn.ru/authors

Обновленное содержание:

Authors are encouraged to submit their papers (4-6 pages) in Russian or English language via the online registration system uConfy.com. The accepted papers will be published in the Conference Proceedings volume (included into the Russian Science Citation Index) prior to the beginning of the Conference.

Template in Russian (файл DCCN2021_LaTeX_RU.zip прилагается к issue)
Template in English (файл DCCN2021_LaTeX_EN.zip прилагается к issue)

[DCCN2021_LaTeX_EN.zip](https://github.com/dccnconf/web21/files/6043462/DCCN2021_LaTeX_EN.zip)
[DCCN2021_LaTeX_RU.zip](https://github.com/dccnconf/web21/files/6043463/DCCN2021_LaTeX_RU.zip)

For your convenience, we made available the DCCN templates in the scientific authoring platform Overleaf:

Overleaf DCCN'2020 Submission Template (RUS) (ссылка: https://www.overleaf.com/latex/templates/dccn2021-submission-template-rus/ckqxxxthwjnf)
Overleaf DCCN'2020 Submission Template (ENG) (ссылка: https://www.overleaf.com/latex/templates/dccn2021-submission-template-eng/gqhbgwrbhckd)

After a peer review and plagiarism check, authors of selected submissions in English, recommended by the Program Committee, will be invited to submit their extended papers (12-15 pages in Springer LNCS template). After a second round of review the accepted extended papers will be published by Springer (approve pending) as a stand-alone volume of selected extended papers (indexed in Scopus and Web of Science).

Please note, that peer review is double-blind. In order to provide the possibility of double-blind peer review, when first submitting the manuscripts the authors are asked to leave empty all fields that may identify the authors (names, emails, affiliations, grant support). In case a submission is not blinded, it will not move on to the review process.

Topics include, but are not limited to the following fields:

Communication networks algorithms and protocols
Wireless and mobile networks
Computer and telecommunication networks control and management
Performance analysis, QoS/QoE evaluation and network efficiency
Evolution of wireless networks toward 5G
Centimeter- and millimeter-wave radio technologies
High-altitude telecommunications platforms
Quantum Information and quantum communication
Machine learning, big data, artificial intelligence
Performance analysis, QoS/QoE evaluation and network efficiency
Analytical modeling and simulation of communication systems
Probabilistic and statistical models in information systems
Queuing theory and reliability theory applications
Machine learning, big data, artificial intelligence
Internet of Things and Fog Computing
Cloud computing, distributed and parallel systems
Security in infocommunication systems
Machine learning, big data, artificial intelligence

**Comment by kozyrevdv** [comment]
необходимо учесть изменения в тексте. он отличается от версии 2020 года.

**Comment by kozyrevdv** [comment]
просьба исправить опечатку: approve pending -> **approval** pending

**Comment by timac11** [comment]
fixed
