### ISSUE TITLE
Technical Sponsors

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web21#6]
Нужно добавить блок "Technical Sponsors" (как ранее: http://2019.dccn.ru/) под блоком "Organizers & sponsors".

Текст для блока: DCCN 2021 is an IEEE (Russia Section) technically co-sponsored (approved) International Conference.

Логотипы для блока: (прилагаются)

![image](https://user-images.githubusercontent.com/47321403/109178481-f17af180-7799-11eb-9771-5e350d71cc0e.png)

![image](https://user-images.githubusercontent.com/47321403/109178663-27b87100-779a-11eb-98f0-69a131a7c5eb.png)

**Comment by kozyrevdv** [comment]
Логотип Region 8 - лишний. Его нужно убрать.
Не увидел текста "DCCN 2021 is an IEEE (Russia Section) technically co-sponsored (approved) International Conference."

**Comment by timac11** [comment]
fixed
