### ISSUE TITLE
Сайт dccn.ru недоступен

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web21#7]
![image](https://user-images.githubusercontent.com/47321403/112836365-2c2abf00-90a3-11eb-9ac5-d0ed982c07fc.png)

**Comment by kozyrevdv** [comment]
@larioandr @timac11

**Comment by larioandr** [comment]
Почему-то автоплатеж не сработал, пополнил руками. Должно включиться через несколько минут.

**Comment by larioandr** [comment]
Исправил.

**Comment by kozyrevdv** [comment]
Отлично, спасибо!
